### ISSUE TITLE
metafinder.py is missing?

### ISSUE THREAD

**Issue by sec0ps** [Josue87/MetaFinder#2]
Just went to do a checkout on a new machine and noticed the metafinder.py script is gone?

**Comment by Josue87** [comment]
Yes, sorry, I'm working on it,  tomorrow or Friday it will be available. For now you can use this old version:
https://github.com/Josue87/MetaFinder/tree/30931051a4b86a9119f39644e3ed6f63bec2863a

**Comment by sec0ps** [comment]
Thanks =)

**Comment by Josue87** [comment]
The code has been adapted. Now you can use it through pip, you don't need metafinder.py anymore.

To install it:
`pip3 install metafinder`

And example of use:

`metafinder -t domain.com -l 10 -o folder_to_save_report -v`
