### ISSUE TITLE
search engines

### ISSUE THREAD

**Issue by sh1va73** [Josue87/MetaFinder#3]
These are the results I get:

Searching in google
[!]  google error GoogleCaptcha, Google Captcha detected

Searching in bing
[!]  bing error HTTP Error 503: Service Unavailable

Searching in baidu
[+] Done

So for me only Baidu is working.

**Comment by Josue87** [comment]
Hello,

When you make too many automatic requests to the search engines, they don't let you continue. It will work again by changing the output IP, or waiting a while. 

Right now it is limited to search 250 files, Google works fine up to that. Bing is still unstable for large searches, I have to check it when I have time.

**Comment by Josue87** [comment]
Bing had a problem in the logic and loop output conditions (OR instead of AND). I will check it this week, thanks!
